// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwfmPBoHm2N81jIEE1JMkjykKuUQivn4Q',
    appId: '1:10919153149:web:8e8bf6f35cc802c6a7dd94',
    messagingSenderId: '10919153149',
    projectId: 'vinos-63de0',
    authDomain: 'vinos-63de0.firebaseapp.com',
    storageBucket: 'vinos-63de0.firebasestorage.app',
    measurementId: 'G-N0RG2QH31B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlB6eJN0GTRiQOr6RrE0ccAapFpTD97s4',
    appId: '1:10919153149:android:17c2a373a19b3a00a7dd94',
    messagingSenderId: '10919153149',
    projectId: 'vinos-63de0',
    storageBucket: 'vinos-63de0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVJamK910QHcO7v7rj1fkbMGpwmIvih8A',
    appId: '1:10919153149:ios:5c497b045939f827a7dd94',
    messagingSenderId: '10919153149',
    projectId: 'vinos-63de0',
    storageBucket: 'vinos-63de0.firebasestorage.app',
    iosBundleId: 'com.example.appBootsup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVJamK910QHcO7v7rj1fkbMGpwmIvih8A',
    appId: '1:10919153149:ios:5c497b045939f827a7dd94',
    messagingSenderId: '10919153149',
    projectId: 'vinos-63de0',
    storageBucket: 'vinos-63de0.firebasestorage.app',
    iosBundleId: 'com.example.appBootsup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwfmPBoHm2N81jIEE1JMkjykKuUQivn4Q',
    appId: '1:10919153149:web:755df14f8c47eedaa7dd94',
    messagingSenderId: '10919153149',
    projectId: 'vinos-63de0',
    authDomain: 'vinos-63de0.firebaseapp.com',
    storageBucket: 'vinos-63de0.firebasestorage.app',
    measurementId: 'G-VYQJL91RDT',
  );

}