// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOlTA9RYYoydP_km_i68UU5WUk2q7dRV0',
    appId: '1:31698346779:web:9e29061db41680f9f269be',
    messagingSenderId: '31698346779',
    projectId: 'bootsup-3d44d',
    authDomain: 'bootsup-3d44d.firebaseapp.com',
    databaseURL: 'https://bootsup-3d44d-default-rtdb.firebaseio.com',
    storageBucket: 'bootsup-3d44d.appspot.com',
    measurementId: 'G-D7YWTLZBD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9o53w6zKq8PhNE-rRf8ZhxRvjRc8v5KE',
    appId: '1:31698346779:android:d2d8d7ae53d8db48f269be',
    messagingSenderId: '31698346779',
    projectId: 'bootsup-3d44d',
    databaseURL: 'https://bootsup-3d44d-default-rtdb.firebaseio.com',
    storageBucket: 'bootsup-3d44d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD38uS8jMVdLVmhKWZ58RvnN8IJOVYcahk',
    appId: '1:31698346779:ios:6e8a8dd075f2697ff269be',
    messagingSenderId: '31698346779',
    projectId: 'bootsup-3d44d',
    databaseURL: 'https://bootsup-3d44d-default-rtdb.firebaseio.com',
    storageBucket: 'bootsup-3d44d.appspot.com',
    androidClientId: '31698346779-1lqkbo27osf6rot2grl5vtmtbpoerosr.apps.googleusercontent.com',
    iosClientId: '31698346779-kk9e2ias71si9eb0t845dejihjjurpuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.appBootsup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD38uS8jMVdLVmhKWZ58RvnN8IJOVYcahk',
    appId: '1:31698346779:ios:6e8a8dd075f2697ff269be',
    messagingSenderId: '31698346779',
    projectId: 'bootsup-3d44d',
    databaseURL: 'https://bootsup-3d44d-default-rtdb.firebaseio.com',
    storageBucket: 'bootsup-3d44d.appspot.com',
    androidClientId: '31698346779-1lqkbo27osf6rot2grl5vtmtbpoerosr.apps.googleusercontent.com',
    iosClientId: '31698346779-kk9e2ias71si9eb0t845dejihjjurpuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.appBootsup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZAMSIuVxz_aQ2C_10d74BhyYKf_WONDQ',
    appId: '1:31698346779:web:269e2ecc0fc27e10f269be',
    messagingSenderId: '31698346779',
    projectId: 'bootsup-3d44d',
    authDomain: 'bootsup-3d44d.firebaseapp.com',
    databaseURL: 'https://bootsup-3d44d-default-rtdb.firebaseio.com',
    storageBucket: 'bootsup-3d44d.appspot.com',
    measurementId: 'G-P58PQX5G33',
  );
}
